[package]
name = "ipfw"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
socket2 = "0.4"
tokio = { version = "1", features = ["full"] }

[profile.release]
strip = true
lto = true